### ISSUE TITLE
배포 환경 구축

### ISSUE THREAD

**Issue by jjunyjjuny** [woowa-techcamp-2021/cashbook-13#2]
## 필수 요구사항

1. - [x] AWS EC2로 인스턴스를 생성한다.
2. - [x] 생성한 인스턴스에 mysql을 설치한다.
3. - [x] PM2를 사용해서 무중단 배포를 구성한다.
4. - [x] Nginx 로 웹 서버를 구성한다.
5. - [x] 자동 배포 기능을 추가한다.  

## 개발방법

- 자동 배포는 GitHub Actions 같은 CI 툴이 아닌 AWS에서 구현한다 (크롬탭으로 배포 스크립트 실행)

## 다른 접근 방법

- 

## 주의할 점

- API키가 외부에 노출되지 않도록 주의한다.

## 예상 완료 시간

- 4h

**Comment by jjunyjjuny** [comment]
단, 프로젝트를 진행하면서 배포가 제대로 되고 있는지 꾸준히 확인

**Comment by jjunyjjuny** [comment]
4번 까지 약 3h, 자동배포에 3h 정도 소요됐습니다

**Comment by jjunyjjuny** [comment]
@negu63  실제 배포 서버 / 개발용 서버를 위한 GitHub OAuth 어플을 두 개 운영하면서 
.env도 개발용/배포서버용으로 구분하기 추가했습니다.

**Comment by negu63** [comment]
넵 좋습니다 배포용은 주소가 달라야 하는 걸 놓치고 있었네요
